import chalk from 'chalk';
import { existsSync, readFileSync, readdirSync } from 'fs';
import { join } from 'path';

export async function explainCommand(opts) {
  const { dir, format } = opts;
  const brainDir = join(dir, '.mnema');

  if (!existsSync(brainDir)) {
    console.log(chalk.yellow('\n  No .mnema/ found.'));
    console.log(`  Run ${chalk.cyan('npx mnemakit init')} first.\n`);
    process.exit(1);
  }

  // Load files
  const projectJson = loadJSON(join(brainDir, 'project.json'));
  const brainMd     = loadText(join(brainDir, 'brain.md'));
  const rulesMd     = loadText(join(brainDir, 'rules.md'));
  const decisions   = loadDecisions(join(brainDir, 'decisions'));

  if (format === 'markdown') {
    outputMarkdown({ projectJson, brainMd, rulesMd, decisions });
  } else {
    outputTerminal({ projectJson, brainMd, rulesMd, decisions, dir });
  }
}

// ── Terminal output ───────────────────────────────────────────────
function outputTerminal({ projectJson, brainMd, rulesMd, decisions, dir }) {
  const p = projectJson || {};
  const name = p.name || require_name(dir);

  console.log('');
  console.log(chalk.bold.cyan('  ┌─ Project Brain ') + chalk.dim('─'.repeat(45)));
  console.log('');

  // Stack
  console.log(`  ${chalk.bold('Stack')}`);
  const stackRows = [
    ['Language',    p.language],
    ['Framework',   p.framework],
    ['Database',    p.database],
    ['ORM',         p.orm],
    ['Testing',     p.testing],
    ['Styling',     p.styling],
    ['Auth',        p.auth],
    ['Deployment',  p.deployment],
    ['Package mgr', p.packageManager],
    ['Build system',p.buildSystem],
    ['CI/CD',       p.cicd],
    ['Containerized', p.containerized ? 'Yes' : null],
  ].filter(([, v]) => v);

  stackRows.forEach(([k, v]) =>
    console.log(`    ${chalk.dim(k.padEnd(14))} ${chalk.cyan(fmt(String(v)))}`)
  );

  if (p.additionalLibs?.length) {
    console.log(`    ${chalk.dim('Libraries'.padEnd(14))} ${chalk.cyan(p.additionalLibs.join(', '))}`);
  }
  console.log('');

  // Decisions
  console.log(`  ${chalk.bold('Decisions')}  ${chalk.dim(`(${decisions.length} recorded)`)}`);
  if (decisions.length === 0) {
    console.log(`    ${chalk.dim('None yet. Run')} ${chalk.cyan('npx mnemakit learn')} ${chalk.dim('to add one.')}`);
  } else {
    decisions.forEach((d, i) => {
      console.log(`    ${chalk.green(String(i + 1).padStart(2))}. ${chalk.white(d.title)}`);
      if (d.reason) console.log(`        ${chalk.dim('→')} ${chalk.dim(d.reason)}`);
    });
  }
  console.log('');

  // Rules summary
  console.log(`  ${chalk.bold('AI Rules')}  ${chalk.dim('(from .mnema/rules.md)')}`);
  if (rulesMd) {
    const enforced = extractSection(rulesMd, 'Enforced rules');
    enforced.slice(0, 5).forEach(r =>
      console.log(`    ${chalk.green('✓')} ${chalk.dim(r)}`)
    );
    if (enforced.length > 5)
      console.log(`    ${chalk.dim(`... +${enforced.length - 5} more in rules.md`)}`);
  }
  console.log('');

  // Footer
  console.log(chalk.dim('  ─'.repeat(25)));
  console.log(`  ${chalk.dim('Files:')} ${chalk.cyan('.mnema/brain.md')}  ${chalk.cyan('rules.md')}  ${chalk.cyan('skills.md')}  ${chalk.cyan('decisions/')}`);
  console.log(`  ${chalk.dim('Update decisions:')} ${chalk.cyan('npx mnemakit learn')}`);
  console.log('');
}

// ── Markdown output ───────────────────────────────────────────────
function outputMarkdown({ projectJson, brainMd, rulesMd, decisions }) {
  const lines = [];
  const p = projectJson || {};

  lines.push('# Project Brain Export');
  lines.push('');
  lines.push(`> Generated by Mnema on ${new Date().toLocaleDateString()}`);
  lines.push('');

  lines.push('## Stack');
  lines.push('');
  lines.push('| Component | Value |');
  lines.push('|-----------|-------|');
  [
    ['Language', p.language], ['Framework', p.framework], ['Database', p.database],
    ['ORM', p.orm], ['Testing', p.testing], ['Styling', p.styling],
    ['Auth', p.auth], ['Deployment', p.deployment],
  ]
    .filter(([, v]) => v)
    .forEach(([k, v]) => lines.push(`| ${k} | ${fmt(String(v))} |`));
  lines.push('');

  if (decisions.length) {
    lines.push('## Architectural Decisions');
    lines.push('');
    decisions.forEach((d, i) => {
      lines.push(`### ${i + 1}. ${d.title}`);
      if (d.reason) lines.push(`**Reason:** ${d.reason}`);
      if (d.alternatives) lines.push(`**Alternatives considered:** ${d.alternatives}`);
      if (d.rejected) lines.push(`**Rejected because:** ${d.rejected}`);
      lines.push('');
    });
  }

  if (rulesMd) {
    lines.push('## AI Rules');
    lines.push('');
    lines.push(rulesMd);
  }

  console.log(lines.join('\n'));
}

// ── Helpers ───────────────────────────────────────────────────────
function loadJSON(path) {
  try { return JSON.parse(readFileSync(path, 'utf8')); } catch { return null; }
}

function loadText(path) {
  try { return readFileSync(path, 'utf8'); } catch { return null; }
}

function loadDecisions(decisionsDir) {
  if (!existsSync(decisionsDir)) return [];
  return readdirSync(decisionsDir)
    .filter(f => f.endsWith('.md') && f !== 'README.md')
    .sort()
    .map(f => parseDecision(join(decisionsDir, f)))
    .filter(Boolean);
}

function parseDecision(path) {
  try {
    const text = readFileSync(path, 'utf8');
    const lines = text.split('\n');
    const title = (lines.find(l => l.startsWith('# Decision')) || '').replace(/^# Decision \d+:\s*/, '').trim();
    const reason = extractSection(text, 'Reason')[0] || '';
    const alternatives = extractSection(text, 'Alternatives considered').join(', ').replace(/^- /gm, '');
    const rejected = extractSection(text, 'Why alternatives were rejected')[0] || '';
    return { title, reason, alternatives, rejected };
  } catch { return null; }
}

function extractSection(md, heading) {
  const lines = md.split('\n');
  const start = lines.findIndex(l => l.includes(heading));
  if (start === -1) return [];
  const section = [];
  for (let i = start + 2; i < lines.length; i++) {
    if (lines[i].startsWith('#')) break;
    const clean = lines[i].replace(/^[-*]\s*/, '').trim();
    if (clean) section.push(clean);
  }
  return section;
}

function fmt(str) {
  if (!str) return '';
  return str.split(/[-_]/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

function require_name(dir) {
  return dir.split('/').pop() || 'project';
}
