/**
 * Generates the four .mnema/ files from a repository profile.
 * Returns { projectJson, brainMd, rulesMd, skillsMd }
 */
export function generateBrain(profile, projectName) {
  return {
    projectJson: buildProjectJson(profile),
    brainMd:     buildBrainMd(profile, projectName),
    rulesMd:     buildRulesMd(profile),
    skillsMd:    buildSkillsMd(profile, projectName),
  };
}

// ── project.json ──────────────────────────────────────────────────
function buildProjectJson(p) {
  const obj = {};
  if (p.language)      obj.language = p.language;
  if (p.framework)     obj.framework = p.framework;
  if (p.database)      obj.database = p.database;
  if (p.orm)           obj.orm = p.orm;
  if (p.testing)       obj.testing = p.testing;
  if (p.deployment)    obj.deployment = p.deployment;
  if (p.buildSystem)   obj.buildSystem = p.buildSystem;
  if (p.packageManager) obj.packageManager = p.packageManager;
  if (p.styling)       obj.styling = p.styling;
  if (p.auth)          obj.auth = p.auth;
  if (p.cicd)          obj.cicd = p.cicd;
  if (p.containerized) obj.containerized = p.containerized;
  if (p.additionalLibs?.length) obj.additionalLibs = p.additionalLibs;
  obj.generatedAt = new Date().toISOString();
  obj.mnemaVersion = '0.1.0';
  return JSON.stringify(obj, null, 2);
}

// ── brain.md ─────────────────────────────────────────────────────
function buildBrainMd(p, projectName) {
  const lines = [];
  lines.push(`# Project Brain — ${projectName}`);
  lines.push('');
  lines.push(`> Generated by Mnema on ${new Date().toLocaleDateString()}.`);
  lines.push('> This file is the source of truth for project context. Keep it updated.');
  lines.push('');

  lines.push('## Stack');
  lines.push('');
  if (p.language)      lines.push(`- **Language:** ${fmt(p.language)}`);
  if (p.framework)     lines.push(`- **Framework:** ${fmt(p.framework)}`);
  if (p.database)      lines.push(`- **Database:** ${fmt(p.database)}`);
  if (p.orm)           lines.push(`- **ORM:** ${fmt(p.orm)}`);
  if (p.testing)       lines.push(`- **Testing:** ${fmt(p.testing)}`);
  if (p.styling)       lines.push(`- **Styling:** ${fmt(p.styling)}`);
  if (p.auth)          lines.push(`- **Auth:** ${fmt(p.auth)}`);
  if (p.deployment)    lines.push(`- **Deployment:** ${fmt(p.deployment)}`);
  if (p.packageManager) lines.push(`- **Package Manager:** ${p.packageManager}`);
  if (p.buildSystem)   lines.push(`- **Build System:** ${fmt(p.buildSystem)}`);
  if (p.cicd)          lines.push(`- **CI/CD:** ${fmt(p.cicd)}`);
  if (p.containerized) lines.push(`- **Containerized:** Yes`);
  if (p.additionalLibs?.length)
    lines.push(`- **Additional Libraries:** ${p.additionalLibs.map(fmt).join(', ')}`);
  lines.push('');

  lines.push('## Architecture');
  lines.push('');
  lines.push(describeArchitecture(p));
  lines.push('');

  lines.push('## Decisions');
  lines.push('');
  lines.push('> Architectural decisions are recorded in `.mnema/decisions/`.');
  lines.push('> Run `npx mnemakit learn` to add a new decision.');
  lines.push('');

  lines.push('## Preferences');
  lines.push('');
  lines.push('> Add team preferences here manually:');
  lines.push('> - e.g. "Prefer functional components over class components"');
  lines.push('> - e.g. "Always co-locate tests next to source files"');
  lines.push('');

  return lines.join('\n');
}

// ── rules.md ─────────────────────────────────────────────────────
function buildRulesMd(p) {
  const rules = buildRules(p);
  const lines = [];

  lines.push('# AI Rules');
  lines.push('');
  lines.push('> These rules are auto-generated from your repository profile.');
  lines.push('> Edit them to match your team\'s actual conventions.');
  lines.push('');
  lines.push('## Enforced rules');
  lines.push('');
  rules.enforced.forEach(r => lines.push(`- ${r}`));
  lines.push('');

  if (rules.avoid.length) {
    lines.push('## Never do these');
    lines.push('');
    rules.avoid.forEach(r => lines.push(`- ❌ ${r}`));
    lines.push('');
  }

  lines.push('## Patterns to follow');
  lines.push('');
  rules.patterns.forEach(r => lines.push(`- ${r}`));
  lines.push('');

  return lines.join('\n');
}

// ── skills.md ────────────────────────────────────────────────────
function buildSkillsMd(p, projectName) {
  const lines = [];
  lines.push('---');
  lines.push(`name: ${projectName}`);
  lines.push(`description: Project context for AI coding agents working on ${projectName}`);
  lines.push('version: 0.1.0');
  lines.push('targets: [cursor, claude-code, windsurf, codex, gemini-cli]');
  lines.push('---');
  lines.push('');
  lines.push(`# ${projectName} — AI Context Skill`);
  lines.push('');
  lines.push('You are working on **' + projectName + '**. Here is everything you need to behave like a long-term team member.');
  lines.push('');

  lines.push('## Stack');
  lines.push('```');
  if (p.language)      lines.push(`Language:        ${fmt(p.language)}`);
  if (p.framework)     lines.push(`Framework:       ${fmt(p.framework)}`);
  if (p.database)      lines.push(`Database:        ${fmt(p.database)}`);
  if (p.orm)           lines.push(`ORM:             ${fmt(p.orm)}`);
  if (p.testing)       lines.push(`Testing:         ${fmt(p.testing)}`);
  if (p.auth)          lines.push(`Auth:            ${fmt(p.auth)}`);
  if (p.styling)       lines.push(`Styling:         ${fmt(p.styling)}`);
  if (p.deployment)    lines.push(`Deployment:      ${fmt(p.deployment)}`);
  if (p.packageManager) lines.push(`Package Manager: ${p.packageManager}`);
  lines.push('```');
  lines.push('');

  lines.push('## Architectural context');
  lines.push('');
  lines.push(describeArchitecture(p));
  lines.push('');

  lines.push('## Rules');
  lines.push('');
  buildRules(p).enforced.forEach(r => lines.push(`- ${r}`));
  lines.push('');

  lines.push('## Decisions');
  lines.push('');
  lines.push('> See `.mnema/decisions/` for full architectural decision records.');
  lines.push('');

  return lines.join('\n');
}

// ── helpers ──────────────────────────────────────────────────────
function fmt(str) {
  if (!str) return '';
  return str
    .split(/[-_]/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function describeArchitecture(p) {
  const parts = [];

  if (p.framework === 'nextjs') {
    parts.push('This is a Next.js application using the App Router.');
    parts.push('Server Components are the default; `\'use client\'` is used only when interactivity is required.');
    if (p.orm === 'prisma') parts.push('Database access goes through Prisma ORM — no raw SQL.');
    if (p.deployment === 'vercel') parts.push('Deployed on Vercel — serverless edge functions where appropriate.');
  } else if (p.framework === 'fastapi') {
    parts.push('This is a FastAPI application with async-first design.');
    parts.push('All route handlers are `async def`. Business logic lives in service classes, not route handlers.');
    if (p.orm === 'sqlalchemy') parts.push('Database access through SQLAlchemy 2.0 async ORM.');
  } else if (p.framework === 'django') {
    parts.push('This is a Django application.');
    parts.push('Follows Django conventions: fat models, thin views, serializers for DRF endpoints.');
  } else if (p.framework === 'express' || p.framework === 'fastify') {
    parts.push(`This is a ${fmt(p.framework)} Node.js API.`);
    parts.push('Routes are thin — business logic lives in service modules.');
  } else if (p.framework === 'remix') {
    parts.push('This is a Remix application. Data loading happens in loaders; mutations in actions.');
  } else if (p.framework === 'sveltekit') {
    parts.push('This is a SvelteKit application. Data loading in +page.server.ts; mutations in form actions.');
  }

  if (p.database && !parts.some(p => p.toLowerCase().includes('database'))) {
    parts.push(`Primary database is ${fmt(p.database)}.`);
  }

  if (p.testing) {
    parts.push(`Tests use ${fmt(p.testing)}.`);
  }

  if (p.containerized) {
    parts.push('The application is containerized with Docker.');
  }

  return parts.length > 0
    ? parts.join(' ')
    : 'Architecture details not yet captured. Run `npx mnemakit learn` to add context.';
}

function buildRules(p) {
  const enforced = [];
  const avoid = [];
  const patterns = [];

  // Language rules
  if (p.language === 'typescript') {
    enforced.push('TypeScript strict mode is enabled — no `any` types');
    enforced.push('All functions that return non-trivial values must have explicit return types');
    avoid.push('Using `any` — use `unknown` and narrow with type guards instead');
  }

  // Framework rules
  if (p.framework === 'nextjs') {
    enforced.push('Default all components to Server Components — add `\'use client\'` only when needed');
    enforced.push('Use Server Actions for all data mutations');
    avoid.push('`useEffect` + `fetch` for data loading — use Server Components instead');
    avoid.push('`pages/` directory — this project uses App Router');
    patterns.push('Wrap interactive UI in small Client Components, keep data-fetching in Server Components');
  }

  if (p.framework === 'fastapi') {
    enforced.push('All route handlers must be `async def`');
    enforced.push('Business logic belongs in service classes, not route handlers');
    avoid.push('Sync route handlers — they block the thread pool');
    avoid.push('Returning ORM objects directly — always use Pydantic response schemas');
  }

  if (p.framework === 'django') {
    enforced.push('Use Django ORM for all database operations — no raw SQL');
    enforced.push('Serializers must validate all input before saving');
    avoid.push('Logic inside views — keep views thin, move logic to model methods or services');
  }

  // ORM rules
  if (p.orm === 'prisma') {
    enforced.push('Use Prisma for all database operations — do not introduce another ORM');
    avoid.push('Raw SQL queries — use Prisma\'s query API');
  }

  if (p.orm === 'drizzle') {
    enforced.push('Use Drizzle ORM for all database operations');
    avoid.push('Mixing Drizzle with another ORM or raw queries');
  }

  // Testing rules
  if (p.testing === 'vitest') {
    enforced.push('Use Vitest for all tests — do not introduce Jest');
    patterns.push('Co-locate unit tests next to source files as `*.test.ts`');
  }
  if (p.testing === 'jest') {
    enforced.push('Use Jest for all tests');
    patterns.push('Co-locate unit tests next to source files as `*.test.ts`');
  }
  if (p.testing === 'pytest') {
    enforced.push('Use pytest for all tests');
    patterns.push('Use fixtures for shared test state — avoid global test setup');
  }

  // Styling
  if (p.styling === 'tailwindcss') {
    enforced.push('Use Tailwind CSS for all styling — no custom CSS files');
    avoid.push('Inline `style={{}}` props — use Tailwind classes');
    avoid.push('CSS modules — Tailwind is the styling system');
  }

  // Auth
  if (p.auth) {
    enforced.push(`Authentication is handled by ${fmt(p.auth)} — do not implement custom auth flows`);
    avoid.push('Rolling custom JWT logic — use the existing auth system');
  }

  // Package manager
  if (p.packageManager === 'pnpm') {
    enforced.push('Use pnpm for all package management — do not use npm or yarn');
  } else if (p.packageManager === 'bun') {
    enforced.push('Use bun for all package management and running scripts');
  }

  // Fallback
  if (enforced.length === 0) {
    enforced.push('Follow existing code conventions in the codebase');
    enforced.push('Match the patterns already present before introducing new ones');
  }

  if (patterns.length === 0) {
    patterns.push('Prefer composition over inheritance');
    patterns.push('Keep functions small and single-purpose');
    patterns.push('Co-locate related code — tests next to source, types near usage');
  }

  return { enforced, avoid, patterns };
}
